version: 0.2
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file samTemplate.yaml  --kms-key-id arn:aws:kms:us-east-1:249879571517:key/62da85f4-2c18-4e6b-963a-e0b3da9dd77a --s3-bucket codepipeline-us-east-1-139285547221 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
