AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    FunctionName: "TimeTestFunction"
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      AutoPublishAlias: "Development"
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  QAAlias:
    DependsOn: TimeFunction
    Type: AWS::Lambda::Alias
    Properties:
     Description: Development
     FunctionName: !Ref TimeFunction
     FunctionVersion: $LATEST
     Name: "QA"
  ProdAlias:
    Type: AWS::Lambda::Alias
    Properties:
     Description: Development
     FunctionName: !Ref TimeFunction
     FunctionVersion: "12"
     Name: "Prod"
